###signUpform
POST http://localhost:3000/signup/
Content-Type: application/json

{
    "name":"hassan aref",
    "email":"11112",
    "password":"12121212",
    "passwordConfirmation":"12121212"
}

###signUpPage
GET http://localhost:3000/signup/

###signInPage
GET http://localhost:3000/signin/

###signInPage
POST http://localhost:3000/signin/
Content-Type: application/json

{
    "email":"111112",
    "password":"12121212"
}

###signout
GET http://localhost:3000/signout/

###getAllUsers
GET http://localhost:3000/getusers/

###getUser
GET http://localhost:3000/getuser/11112/

###updateUser
PATCH http://localhost:3000/updateuser/11112/
Content-Type: application/json

{
    "name":"hassa"
    
}

###deleteUser
DELETE http://localhost:3000/deleteuser/11112/

###addTime
POST http://localhost:3000/addtime/
Content-Type: application/json

{
    "date":"2009-12-3",
    "distance":100,
    "time":10
}

###getAllTimes
GET http://localhost:3000/gettimes/

###getOneTime
GET http://localhost:3000/getTime/2009-12-1/

###updateTime
PATCH http://localhost:3000/update/2009-12-2/
Content-Type: application/json

{
    "time":30
}

###deleteTime
DELETE http://localhost:3000/deletetime/2009-12-1/
